version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - '3001:3000'
    depends_on:
      - postgres
      - rabbitmq

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - rabbitmq

volumes:
  pgdata:
    driver: local