FROM node:18

# # Install PostgreSQL client and ts-node
# RUN apt-get update && apt-get install -y postgresql-client

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Install ts-node and tsconfig-paths as global dependencies
RUN npm install -g ts-node tsconfig-paths

# Copy the rest of the application files
COPY . .

# Run seed process
RUN npm run seed
# Build TypeScript to JavaScript
RUN npm run build

# Copy wait-for script and give execute permission
# COPY wait-for.sh .
# RUN chmod +x wait-for.sh

# Run seed process with logs before starting the app
# CMD ["sh", "-c", "./wait-for.sh postgres 5432 && npm run seed && node dist/main.js"]
# CMD ["sh", "-c", "./wait-for.sh postgres 5432 && node dist/seeder.js && node dist/main.js"]

# Debug: make sure dist exists and has main.js
RUN ls -la dist

# Start the app
CMD ["node", "dist/main"]

